"""Synthetic cohort data generation.

IMPORTANT — read before using this module: every value produced here is
randomly generated by ``numpy.random.Generator`` from a fixed seed. None of
it originates from real individuals, real wearable devices, real electronic
health records, or any clinical or genomic dataset. It exists purely to give
the rest of the pipeline (knowledge-graph construction, model training, CLI
demos, tests) something realistic-shaped and reproducible to operate on.

Do not use output from this module to make real health, diagnostic, or
clinical decisions.
"""

from __future__ import annotations

import numpy as np
import pandas as pd

from vitagraph.config import BioAgeFormulaWeights, SignalBaseline

#: Canonical feature columns consumed by BioAgeEstimator, in a stable order.
FEATURE_COLUMNS: list[str] = [
    "chronological_age",
    "heart_rate_avg",
    "hrv_avg",
    "sleep_hours_avg",
    "activity_level",
    "environmental_exposure",
]

TARGET_COLUMN: str = "biological_age"


class SyntheticCohortGenerator:
    """Generates synthetic per-person feature tables with a simulated biological-age label.

    Example:
        >>> gen = SyntheticCohortGenerator(seed=42)
        >>> cohort = gen.generate(num_samples=500)
        >>> sorted(cohort.columns) == sorted(FEATURE_COLUMNS + [TARGET_COLUMN])
        True
    """

    def __init__(
        self,
        baseline: SignalBaseline | None = None,
        formula: BioAgeFormulaWeights | None = None,
        seed: int = 42,
    ) -> None:
        self.baseline = baseline or SignalBaseline()
        self.formula = formula or BioAgeFormulaWeights()
        self.rng = np.random.default_rng(seed)

    def generate(self, num_samples: int = 100) -> pd.DataFrame:
        """Generates a cohort of synthetic individuals.

        Args:
            num_samples: Number of synthetic individuals to generate.

        Returns:
            DataFrame with columns ``FEATURE_COLUMNS + [TARGET_COLUMN]``.

        Raises:
            ValueError: If ``num_samples`` is not positive.
        """
        if num_samples <= 0:
            raise ValueError("num_samples must be positive")

        b = self.baseline
        rng = self.rng

        chronological_age = rng.integers(20, 70, num_samples).astype(float)
        heart_rate_avg = np.clip(
            rng.normal(b.heart_rate_mean, b.heart_rate_std, num_samples),
            b.heart_rate_min,
            b.heart_rate_max,
        )
        hrv_avg = np.clip(
            rng.normal(b.hrv_mean_ms, b.hrv_std_ms, num_samples),
            b.hrv_min_ms,
            b.hrv_max_ms,
        )
        sleep_hours_avg = np.clip(
            rng.normal(b.sleep_hours_mean, b.sleep_hours_std, num_samples),
            b.sleep_hours_min,
            b.sleep_hours_max,
        )
        activity_level = np.clip(
            rng.normal(b.activity_level_mean, b.activity_level_std, num_samples),
            b.activity_level_min,
            b.activity_level_max,
        )
        environmental_exposure = np.clip(
            rng.normal(b.environmental_exposure_mean, b.environmental_exposure_std, num_samples),
            b.environmental_exposure_min,
            b.environmental_exposure_max,
        )

        f = self.formula
        noise = rng.normal(0, f.noise_std, num_samples)
        biological_age = (
            chronological_age
            + f.hr_weight * (heart_rate_avg - b.heart_rate_mean)
            + f.sleep_weight * (b.sleep_hours_mean - sleep_hours_avg)
            + f.activity_weight * (b.activity_level_mean - activity_level)
            + f.hrv_weight * (b.hrv_mean_ms - hrv_avg)
            + f.environmental_weight * environmental_exposure
            + noise
        )
        biological_age = np.clip(
            biological_age,
            chronological_age - f.max_deviation_years,
            chronological_age + f.max_deviation_years,
        )

        return pd.DataFrame(
            {
                "chronological_age": chronological_age,
                "heart_rate_avg": heart_rate_avg,
                "hrv_avg": hrv_avg,
                "sleep_hours_avg": sleep_hours_avg,
                "activity_level": activity_level,
                "environmental_exposure": environmental_exposure,
                "biological_age": biological_age,
            }
        )
